# -*- coding: utf-8 -*-
"""Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9x1YKQDKWs_30xa-RzaWpktNWg7p2q0
"""

from google.colab import files

import pandas as pd

import matplotlib.pyplot as plt

import numpy as np

import statsmodels.formula.api as sm

"""Uploading"""

Housing = files.upload()

Housing = pd.read_excel('Housing.xlsx')

type(Housing)

"""Histogram"""

price = Housing['price']

stories = Housing['stories']

plt.hist(price.dropna(),bins=15)
plt.xlabel('House Price in $')
plt.ylabel('Frequency')
plt.show()

plt.hist(stories.dropna(),bins=15)
plt.xlabel('# of stories')
plt.ylabel('Frequency')
plt.show()





